# Generated by Django 5.2.7 on 2025-10-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
    ]
